# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fijos:
            memory:
                users:
                    profesor:
                        password: oretania
                        roles: 'ROLE_DOCENTE'
                    ordenanza:
                        password: ordenanza
                        roles: 'ROLE_ORDENANZA'
                    secretario:
                        password: secretario
                        roles: 'ROLE_SECRETARIO'

    role_hierarchy:
        ROLE_SECRETARIO: ['ROLE_DOCENTE', 'ROLE_GESTOR_PRESTAMOS']
        ROLE_DOCENTE: 'ROLE_USER'
        ROLE_ORDENANZA: ['ROLE_GESTOR_PRESTAMOS', 'ROLE_USER']

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
